### ISSUE TITLE
time buffer

### ISSUE THREAD

**Issue by lucasart** [lucasart/Demolito#59]
configurable (eg. high value for slow GUI like Arena, low value for low latency cutechess-cli).

**Comment by stockfishdeveloper** [comment]
As I understand, you want a UCI option to control the amount of "lag time" we should prepare for. This would mainly be used with a slow GUI. I know several other engines use this.

I think a sensible amount would be 30-50 ms.
What do you think?

**Comment by lucasart** [comment]
depends on the GUI. for cutechess-cli, 30ms is enough. For Arena, you probably need 1 second...

**Comment by stockfishdeveloper** [comment]
I see.

**Comment by stockfishdeveloper** [comment]
Ok, my schedule has been very tight lately, so I haven't had much time to work on the engine.
I'm still very much interested in working on it. I'll work on this next.
Obviously we want a UCI option, but what exactly has to be avoided because of lag? Losing on time? In that case we would basically subtract our buffer time from the available search time, right?
